energiaSolar/apps/produtos/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r"^$", views.ProdutoView.as_view(), name="produto_index"),
    url(r"^produto/detalhes/(?P<pk>[0-9]+)/$",views.ProdutoDetailView.as_view(), name="produto_show"),
    url(r"^produto/cadastrar/$",views.produto_create, name="produto_create"),
    url(r"^produto/(?P<pk>[0-9]+)/editar/$",views.produto_edit, name="produto_edit"),
    url(r"^produto/(?P<pk>[0-9]+)/excluir/$",views.produto_delete, name="produto_delete"),
    url(r"^itens/$", views.ItemView.as_view(), name="itens_index"),
    url(r"^produto/itens/(?P<pk>[0-9]+)/editar/$",views.itens_edit, name="itens_edit"),
    url(r"^produto/itens/(?P<pk>[0-9]+)/detalhes/$",views.ItemDetailView.as_view(), name="item_show"),
]

energiaSolar/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from .apps.authorization import views
from .apps.core.views import home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', login_required(home), name="root_path" ),
    url(r'^core/', include('energiaSolar.apps.core.urls', namespace='core')),
    url(r'^auth/',
        include('energiaSolar.apps.authorization.urls', namespace='authorization')),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^clientes/',
        include('energiaSolar.apps.clientes.urls', namespace='clientes')),
    url(r'^produtos/',
        include('energiaSolar.apps.produtos.urls', namespace='produtos')),
    url(r'^administracao/',
         include('energiaSolar.apps.administracao.urls', namespace='administracao')),
    url(r'^configuracoes/',
        include('energiaSolar.apps.configuracoes.urls', namespace='configuracoes')),
    url(r'^orcamentos/',
        include('energiaSolar.apps.orcamentos.urls', namespace='orcamentos')),
    url(r'^fornecedores/',
        include('energiaSolar.apps.fornecedores.urls', namespace='fornecedores'))
]

energiaSolar/apps/produtos/forms.py
# -*- coding: utf-8 -*-
from django import forms
from datetime import datetime
from .models import *
from localflavor.br.forms import BRStateChoiceField
from django.core.validators import validate_integer

class SearchProduto(forms.Form):
    """Formulário para consulta de produtos da view que lista produtos
    de forma genérica"""

    codigo = forms.CharField(max_length=20, required=False, label="Código")
    tipo_produto = forms.ModelChoiceField(queryset=TipoProduto.objects.all().order_by('descricao'), required=False,
                                          label="Tipo do Produto")
    fornecedor = forms.ModelChoiceField(queryset=Fornecedor.objects.all(), required=False)

class SearchItem(forms.Form):
    """Formulário para consulta de produtos da view que lista produtos
    de forma genérica"""

    descricao = forms.CharField(max_length=20, required=False)

class ProdutoCreateForm(forms.ModelForm):
    """Formulário para criação de produtos"""
    tipo_produto = forms.ModelChoiceField(queryset=TipoProduto.objects.exclude(pk=0).order_by('descricao'), required=True, label="Tipo do Produto")
    fornecedor = forms.ModelChoiceField(queryset=Fornecedor.objects.all(), required=True)
    valor = forms.DecimalField(required=True)
    estrutura_metalica = forms.IntegerField(required=False, label="Quant. de Est. Metálica")
    potencia_inversor = forms.DecimalField(required=False, label="Potência em Kw")
    quantidade_inversor = forms.IntegerField(required=False, label="Quantidade")
    marca_inversor = forms.CharField(required=False, label="Marca")
    potencia_placa = forms.DecimalField(required=False, label="Potência em Wp")
    quantidade_placa = forms.IntegerField(required=False, label="Quantidade")
    marca_placa = forms.CharField(required=False, label="Marca")
    percentual_placas = forms.IntegerField(required=False, label="Porcentagem Placas")
    percentual_inversores = forms.IntegerField(required=False, label="Porcentagem Inversores")

    class Meta:
        fornecedor = forms.ModelChoiceField(queryset=Fornecedor.objects.all())
        model = Produto
        exclude = ['servico', 'valor_servico', 'valor_est_metalica']
        labels = {
            'descricao': 'Descrição',
            'porcentagem_servico_produto': 'Porcentagem do Serviço',
            'porcentagem_estrutura_produto': 'Porcentagem Est. Metálica',
        }

class ItensCreateForm(forms.ModelForm):
    """Formulário para criação de itens"""
    tipo_item = forms.ModelChoiceField(required=False, queryset=TipoItem.objects.all(), label="Tipo do Item")
    potencia = forms.DecimalField(required=False, label="Potência")
    quantidade = forms.IntegerField(required=False, label="Quantidade")
    marca = forms.CharField(required=False, label="Marca")
    valor_item = forms.DecimalField(required=False)

    class Meta:
        model = Item
        exclude = ['produto']
        labels = {
            'descricao_item': 'Descrição do Item'
        }

class ProdutoEditForm(forms.ModelForm):
    """Formulário para criação de produtos"""
    tipo_produto = forms.ModelChoiceField(queryset=TipoProduto.objects.exclude(pk=0).order_by('descricao'), required=True, label="Tipo do Produto")
    fornecedor = forms.ModelChoiceField(queryset=Fornecedor.objects.all(), required=True)
    valor = forms.DecimalField(required=True)
    estrutura_metalica = forms.IntegerField(required=False, label="Quant. de Est. Metálica")
    potencia_inversor = forms.DecimalField(required=False, label="Potência")
    quantidade_inversor = forms.IntegerField(required=False, label="Quantidade")
    marca_inversor = forms.CharField(required=False, label="Marca")
    potencia_placa = forms.DecimalField(required=False, label="Potência")
    quantidade_placa = forms.IntegerField(required=False, label="Quantidade")
    marca_placa = forms.CharField(required=False, label="Marca")

    class Meta:
        fornecedor = forms.ModelChoiceField(queryset=Fornecedor.objects.all())
        model = Produto
        exclude = ['servico', 'valor_servico', 'valor_est_metalica']
        labels = {
            'descricao': 'Descrição',
            'porcentagem_servico_produto': 'Porcentagem do Serviço',
            'porcentagem_estrutura_produto': 'Porcentagem Est. Metálica',
        }

energiaSolar/apps/produtos/views.py
# -*- coding: utf-8 -*-
from django.urls import reverse_lazy as reverse
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import get_object_or_404, redirect, render
from ..core.generic_views import SearchCustomView, CustomDetailView
from .forms import *
from .models import Produto, Item, TipoItem, TipoProduto, Fornecedor
from django.http import HttpResponse
import math

@method_decorator(login_required, name='dispatch')
class ProdutoView(SearchCustomView):
    """
    View para consulta de ocorrências
    """
    form_class = SearchProduto
    model = Produto
    order_field = "codigo"
    template_name = "produtos/index.html"
    page_title = "Produtos"
    breadcrumbs = [
        (reverse("root_path"), "Início"),
        (reverse("produtos:produto_index"), "Produtos")
    ]

    def get_queryset(self):
        """
        Altera o filtro do cliente ::
        """
        queryset = super(ProdutoView, self).get_queryset()
        form = self.form_class(self.request.GET)
        form.is_valid()
        query = {}

        # Criando nova biblioteca com os valores preenchidos
        for key, value in form.cleaned_data.items():
            if value and value != "":
                query[key] = value

        queryset = queryset.filter(**query)
        return queryset

@method_decorator(login_required, name='dispatch')
class ProdutoDetailView(CustomDetailView):
    """
    View para exibição dos detalhes do produto
    """
    model = Produto
    template_name = "produtos/detail.html"
    page_title = "Detalhes do Produto"

    def get_context_data(self, **kwargs):
        context = super(ProdutoDetailView, self).get_context_data(**kwargs)
        context["breadcrumbs"] = [
            (reverse("root_path"), "Início"),
            (reverse("produtos:produto_index"), "Produtos"),
            ("#", self.get_object().id)
        ]

        context["itens"] = self.get_object().item_set.order_by("descricao_item")

        return context

@method_decorator(login_required, name='dispatch')
class ItemView(SearchCustomView):
    """
    View para consulta de itens
    """
    form_class = SearchItem
    model = Item
    order_field = "descricao_item"
    template_name = "produtos/item_index.html"
    page_title = "Itens"
    breadcrumbs = [
        (reverse("root_path"), "Início"),
        (reverse("produtos:itens_index"), "Itens")
    ]

    def get_queryset(self):
        """
        Altera o filtro do cliente ::
        """
        queryset = super(ItemView, self).get_queryset()
        form = self.form_class(self.request.GET)
        form.is_valid()
        query = {}

        # Criando nova biblioteca com os valores preenchidos
        for key, value in form.cleaned_data.items():
            if value and value != "":
                query[key] = value

        queryset = queryset.filter(**query)
        return queryset

@method_decorator(login_required, name='dispatch')
class ItemDetailView(CustomDetailView):
    """
    View para exibição dos detalhes do produto
    """
    model = Item
    template_name = "produtos/item_detail.html"
    page_title = "Detalhes do Item"

    def get_context_data(self, **kwargs):
        context = super(ItemDetailView, self).get_context_data(**kwargs)
        context["breadcrumbs"] = [
            (reverse("root_path"), "Início"),
            (reverse("produtos:produto_index"), "Produtos"),
            ("#", self.get_object().id)
        ]
        return context

@login_required
@permission_required("produtos.add_produto", raise_exception=True)
def produto_create(request):
    """View para Criar um produto"""

    breadcrumbs = [
        (reverse("root_path"), "Início"),
        (reverse("produtos:produto_index"), "Produtos"),
        (reverse("produtos:produto_create"), "Novo Produto")
    ]

    form = ProdutoCreateForm()
    itens = ItensCreateForm()

    if request.method == 'POST':
        form = ProdutoCreateForm(request.POST)
        itens = ItensCreateForm(request.POST)

        if form.is_valid():
            produto = form.save(commit=False)
            tipo_produto = TipoProduto.objects.get(pk=form['tipo_produto'].value())
            fornecedor = Fornecedor.objects.get(pk=form['fornecedor'].value())
            total_porcentagens = 0

            #calcula porcentagem de valor
            if tipo_produto.descricao != "Avulso":
                valor_produto = form.cleaned_data['valor']
                percentual_servico = form.cleaned_data['porcentagem_servico_produto']
                percentual_metalica = form.cleaned_data['porcentagem_estrutura_produto']
                qtd_est_metalica = form.cleaned_data['estrutura_metalica']
                potencia_inversor = form.cleaned_data['potencia_inversor']
                quantidade_inversor = form.cleaned_data['quantidade_inversor']
                marca_inversor = form.cleaned_data['marca_inversor']
                potencia_placa = form.cleaned_data['potencia_placa']
                quantidade_placa = form.cleaned_data['quantidade_placa']
                marca_placa = form.cleaned_data['marca_placa']
                percentual_placas = form.cleaned_data["percentual_placas"]
                percentual_inversores = form.cleaned_data["percentual_inversores"]

                produto.potencia_inversor = potencia_inversor
                produto.quantidade_inversor = quantidade_inversor
                produto.marca_inversor = marca_inversor
                produto.potencia_placa = potencia_placa
                produto.quantidade_placa = quantidade_placa
                produto.marca_placa = marca_placa

                potencia = float(quantidade_placa * potencia_placa)
                potencia_codigo = abs(int(potencia * (-100)))
                produto.codigo = str(str(fornecedor.codigo) + str(potencia_codigo))
                produto.potencia_produto = (potencia / 1000)

                if not (percentual_metalica and percentual_servico and percentual_inversores and percentual_placas):
                    produto.porcentagem_estrutura_produto = 3
                    produto.porcentagem_servico_produto = 2
                    produto.percentual_inversores = 30
                    produto.percentual_placas = 65
                    produto.estrutura_metalica = 1

                    produto.valor_inversores = (30 / 100) * float(valor_produto)
                    produto.valor_placas = (65 / 100) * float(valor_produto)
                    produto.valor_servico = (2 / 100) * float(valor_produto)
                    produto.valor_est_metalica = (3 / 100) * float(valor_produto)
                else:
                    produto.porcentagem_estrutura_produto = percentual_metalica
                    porcentagem_servico_produto = percentual_servico
                    produto.estrutura_metalica = 1
                    produto.percentual_inversores = percentual_inversores
                    produto.percentual_placas = percentual_placas

                    produto.valor_inversores = (percentual_inversores / 100) * float(valor_produto)
                    produto.valor_placas = (percentual_placas / 100) * float(valor_produto)
                    produto.valor_servico = (percentual_servico / 100) * float(valor_produto)
                    produto.valor_est_metalica = (percentual_metalica / 100) * float(valor_produto)

                produto.valor_individual_placas = (float(valor_produto) / quantidade_placa)
                produto.valor_individual_inversor = (float(valor_produto) / quantidade_inversor)

            else:
                produto.codigo = fornecedor.codigo
                produto.valor = form.cleaned_data['valor']

            produto.save()

            if itens.is_valid():
                item = itens.save(commit=False)
                # Cadastra os itens do produto
                tipos = request.POST.getlist('tipo_item[]')
                descricoes = request.POST.getlist('descricao_item[]')
                potencias = request.POST.getlist('potencia[]')
                quantidades = request.POST.getlist('quantidade[]')
                marcas = request.POST.getlist('marca[]')
                valores = request.POST.getlist('valor_item[]')

                try:
                    for tipo, descricao_item, potencia, quantidade, marca, valor in zip(tipos, descricoes,
                                                                                              potencias, quantidades,
                                                                                              marcas, valores):
                        tipo = int(tipo)
                        tipo_item = TipoItem.objects.get(pk=tipo)
                        prod = Produto.objects.get(pk=produto.pk)
                        item_obj = Item()
                        item_obj.descricao_item = descricao_item
                        item_obj.potencia = potencia
                        item_obj.quantidade = quantidade
                        item_obj.marca = marca
                        item_obj.valor_item = valor
                        item_obj.tipo_item = tipo_item
                        item_obj.valor_unitario = item.valor_unitario = (float(valor) / int(quantidade))
                        item_obj.produto = prod
                        item_obj.save()
                except:
                    None

            messages.success(request, "Produto cadastrado com sucesso")
            return redirect(reverse("produtos:produto_show", args=[produto.pk]))

    return render(request, "produtos/cadastro.html", locals())

@login_required
@permission_required("produtos.add_produto", raise_exception=True)
def produto_edit(request, pk):
    """"View para Editar os Produtos"""
    produto = get_object_or_404(Produto, pk=pk)

    breadcrumbs = [
        (reverse("root_path"), "Início"),

energiaSolar/apps/produtos/templates/produtos/detail.html
{% extends "clientes/base.html" %}
{% load humanize %}
{% load static bootstrap3 core %}
{% block head_stylesheet %}
<link rel="stylesheet" href="{% static 'css/produto.css' %}">
{% endblock head_stylesheet %}

{% block content %}
<div class="detail-page">
  <div class="container-fluid">
    <div class="row">
      <div class="col">

        <div class="section-bar">
          <h2 class="title">{{ page_title }}: {{ produto.id }}</h2>
        </div>
        <table class="table table-bordered table-striped">
          <tr>
            <td><strong>Código:</strong><br> {{ produto.codigo|default:"Não informado" }}</td>
            <td><strong>Tipo do Produto:</strong><br> {{ produto.tipo_produto|default:"Não informado" }}</td>
            <td><strong>Fornecedor:</strong><br> {{ produto.fornecedor|default:"Não informado" }}</td>
            <td><strong>Valor do Produto:</strong><br>R$ {{ produto.valor|intcomma|default:"Não informado" }}</td>
            <td><strong>Descrição:</strong><br> {{ produto.descricao|default:"Não informado" }}</td>
            {% if produto.tipo_produto.descricao == "Gerador" %}
              <td><strong>Potência:</strong><br> {{ produto.potencia_produto|default:"Não informado" }} KW</td>
            {% endif %}
          </tr>
        </table>
         {% if produto.tipo_produto.descricao == "Gerador" %}
           <h4>Componentes do Gerador</h4>
          <table class="table table-bordered table-striped">
            <tr>
              <td><strong>Tipo:</strong><br> Inversor</td>
              <td><strong>Quantidade:</strong><br> {{ produto.quantidade_inversor|default:"Não informado" }}</td>
              <td><strong>Marca:</strong><br> {{ produto.marca_inversor|default:"Não informado" }}</td>
              <td><strong>Potência:</strong><br> {{ produto.potencia_inversor|default:"Não informado" }} KW</td>
               <td><strong>Valor:</strong><br> R$ {{ produto.valor_inversores|intcomma|default:"Não informado" }} ({{ produto.percentual_inversores|floatformat:0|intcomma}}%)</td>
            </tr>
            <tr>
              <td><strong>Tipo:</strong><br> Placas</td>
              <td><strong>Quantidade:</strong><br> {{ produto.quantidade_placa|default:"Não informado" }}</td>
              <td><strong>Marca:</strong><br> {{ produto.marca_placa|default:"Não informado" }}</td>
              <td><strong>Potência:</strong><br> {{ produto.potencia_placa|default:"Não informado" }} W</td>
              <td><strong>Valor:</strong><br> R$ {{ produto.valor_placas|intcomma|default:"Não informado" }} ({{ produto.percentual_placas|floatformat:0|intcomma}}%)</td>
            </tr>
          {% endif %}
          {% if produto.tipo_produto.descricao != 'Avulso' %}
            <tr>
              <td><strong>Percentual Est. Metalica:</strong><br>{{ produto.porcentagem_estrutura_produto|default:"Não informado" }} %</td>
              <td><strong>Valor Est. Metalica:</strong><br> R$ {{ produto.valor_est_metalica|intcomma|default:"Não informado" }} </td>
              <td><strong>Percentual Serviço:</strong><br>{{ produto.porcentagem_servico_produto|default:"Não informado" }} %</td>
              <td colspan="2"><strong>Valor Serviço:</strong><br>R$ {{ produto.valor_servico|intcomma|default:"Não informado" }}</td>
            </tr>
          {% endif %}
        </table>
        {% if itens %}
          <h4>Itens do Produto</h4>
          <table class="table table-bordered table-striped">
            <th>Ações</th>
            <th>Descrição</th>
            <th>Tipo</th>
            <th>Marca</th>
            <th>Potência</th>
            <th>Quantidade</th>
            <th>Valor</th>
            <th>Valor Unitário</th>
            {% for item in itens %}
              <tr>
                <td>
                  <a class="btn-magnify" href="{% url 'produtos:itens_edit' item.pk %}" title="Editar">
                      <span class="mdi mdi-pencil mdi-18px"></span>
                  </a>
                </td>
                <td>{{ item.descricao_item|default:"Não informado" }}</td>
                <td>{{ item.tipo_item|default:"Não informado" }}</td>
                <td>{{ item.marca|default:"Não informado" }}</td>
                <td>{{ item.potencia|default:"Não informado" }} KW</td>
                <td>{{ item.quantidade|default:"Não informado" }}</td>
                <td>R$ {{ item.valor_item|default:"Não informado" }}</td>
                <td>R$ {{ item.valor_unitario|default:"0" }}</td>
              </tr>
            {% endfor %}
          </table>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="form-row">
    <div class="form -btn-actions col">
      <a href="{% url 'produtos:produto_index' %}" class="btn btn-default"><< Voltar</a>
    </div>
  </div>
</div>
{% include "util/paginator.html" %}
{% endblock %}

energiaSolar/apps/produtos/templates/produtos/editar.html
{% extends "layout/base.html" %}
{% load static bootstrap3 core %}
{% block head_stylesheet %}
<link rel="stylesheet" href="{% static 'css/produto_edit.css' %}">
{% endblock head_stylesheet %}
{% bootstrap_form_errors form error_types="non_field_errors" %}

{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <div class="section-bar">
        <h1 class="title">Editar Produto</h1>
      </div>
    </div>
  </div>
  <div class="row list">
    <div class="col">
      <form class="form" method="POST" novalidate>
        {% csrf_token %}
        {% bootstrap_form_errors form error_types="all" %}
          {{ form.non_field_errors.as_text }}
          {{ itens.non_field_errors.as_text }}
            <div class="form-row">
                 <div class="col-3">
                  {% bootstrap_field form.tipo_produto required_css_class="required" %}
                </div>
                <div class="col-3">
                  {% bootstrap_field form.fornecedor required_css_class="required" %}
                </div>
                <div class="col-3">
                  {% bootstrap_field form.descricao required_css_class="required" %}
                </div>
                 <div class="col-3">
                  {% bootstrap_field form.valor required_css_class="required" %}
                </div>
            </div>
          {% if produto.tipo_produto.descricao == "Gerador" %}
          <div class="componentes-produto">
              <h4>Inversor</h4>
              <div class="form-row">
                <div class="col-4">
                  {% bootstrap_field form.quantidade_inversor required_css_class="required" %}
                </div>
                <div class="col-4">
                  {% bootstrap_field form.marca_inversor required_css_class="required" %}
                </div>
                <div class="col-4">
                  {% bootstrap_field form.potencia_inversor required_css_class="required" %}
                </div>
              </div>
              <h4>Placas</h4>
              <div class="form-row">
                <div class="col-4">
                  {% bootstrap_field form.quantidade_placa required_css_class="required" %}
                </div>
                <div class="col-4">
                  {% bootstrap_field form.marca_placa  required_css_class="required" %}
                </div>
                <div class="col-4">
                  {% bootstrap_field form.potencia_placa  required_css_class="required" %}
                </div>
              </div>
          </div>
          {% endif %}
            <div class="form-row">
              <div class="form -btn-actions col">
                <button class="btn btn-success mr-2">Salvar</button>
                <a href="{% url 'produtos:produto_index' %}" class="btn">Cancelar</a>
              </div>
            </div>
        </form>
    </div>
  </div>
</div>
{% include "util/paginator.html" %}
{% endblock %}
{% block extra_js %}
<script type="text/javascript" src="{% static 'js/jquery.mask.min.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
<script src="{% static 'js/produto_edit.js' %}" charset="utf-8"></script>
{% endblock extra_js %}

energiaSolar/apps/produtos/templates/produtos/index.html
{% extends "clientes/base.html" %}
{% load humanize %}
{% load l10n %}
{% load static bootstrap3 core %}
{% block head_stylesheet %}
<link rel="stylesheet" href="{% static 'css/produto.css' %}">
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.0/bootstrap-table.min.css" rel="stylesheet"/>

{% endblock head_stylesheet %}

{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <div class="section-bar">
        <h1 class="title">{{ page_title }}</h1>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <!-- search form -->
      <form class="form form-flex form-search-cerin">
        {% bootstrap_form form %}
        <div class="form-group">
          <div id="general-search-button"></div>
        </div>
      </form>
    </div>
  </div>
  <div id="messageDelete" class="alert alert-success" role="alert">
    Produto excluido!
  </div>
      <table id="produtos" class="table table-bordered table-striped" data-toggle="table" style="width:100%">
        <thead>
          <th>Ações</th>
          <th data-field="codigo" data-sortable="true">Código</th>
          <th data-field="fornecedor" data-sortable="true">Fornecedor</th>
          <th data-field="tipo" data-sortable="true">Tipo</th>
          <th data-field="preco" data-sortable="true" data-sorter="sort_diero">Preço</th>
          <th data-field="descricao" data-sortable="true">Descrição</th>
        </thead>
        <tbody>
          {% for produto in object_list %}
            <tr>
              <td>
                <a class="btn-magnify" href="{% url 'produtos:produto_show' produto.pk %}" title="Ver detalhes">
                  <span class="mdi mdi-magnify mdi-18px"></span>
                </a>
                <a class="btn-magnify" href="{% url 'produtos:produto_edit' produto.pk %}" title="Editar">
                  <span class="mdi mdi-pencil mdi-18px"></span>
                </a>
                <a class="btn-magnify" href="javascript:produtoDelete({{produto.pk}});" title="Excluir">
                  <span class="mdi mdi-delete mdi-18px"></span>
                </a>
              </td>
              <td>{{ produto.codigo }}</td>
              <td>{{ produto.fornecedor }}</td>
              <td>{{ produto.tipo_produto }}</td>
              <td>R$ {{ produto.valor|intcomma  }}</td>
              <td>{{ produto.descricao|default:"Não informado" }}</td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
    <!-- Modal responsável pela confirmação
        da exclusão de um produto -->
        <div id="myModal" class="modal" tabindex="-1" role="dialog">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Confirmar Exclusão</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p>Você tem certeza que deseja excluir permanentemente esse produto?</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" id="excluirProduto" class="btn btn-primary">Excluir</button>
              </div>
            </div>
          </div>
        </div>
</div>
{% include "util/paginator.html" %}
{% endblock %}

{% block extra_js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.0/bootstrap-table.min.js"></script>
<script>
  $('#messageDelete').hide();
  function produtoDelete(pk){
    $('#myModal').modal('toggle')
    $( "#excluirProduto" ).click(function() {
      $.ajax({
        url: '/produtos/produto/'+pk+'/excluir',
        success: function(data) {
          location.reload();
        }
      });
    });
  };

   function sort_diero(a, b, rowA, rowB) {
    a = +(a.replace('.', '').replace(',', '.').substring(3));
    b = +(b.replace('.', '').replace(',', '.').substring(3));

    if (a > b) return 1;
    if (a < b) return -1;
    
    return 0;
  }
</script>
{% endblock %}

energiaSolar/apps/produtos/templates/produtos/item_index.html
{% extends "clientes/base.html" %}
{% load static bootstrap3 core %}

{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <div class="section-bar">
        <h1 class="title">{{ page_title }}</h1>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <!-- search form -->
      <form class="form form-flex form-search-cerin">
        {% bootstrap_form form %}
        <div class="form-group">
          <div id="general-search-button"></div>
        </div>
      </form>
    </div>
  </div>
  <div class="row">
      <table class="table table-striped table-bordered table-responsive">
        <thead>
          <th>Ações</th>
          <th>Potência</th>
          <th>Marca</th>
          <th>Descrição</th>
        </thead>
        <tbody>
          {% for item in object_list %}
            <tr>
              <td>
                <a class="btn-magnify" href="{% url 'produtos:itens_edit' item.pk %}" title="Editar">
                  <span class="mdi mdi-pencil mdi-18px"></span>
                </a>
              </td>
              <td>{{ item.potencia }} KW</td>
              <td>{{ item.marca }}</td>
              <td>{{ item.descricao_item }}</td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
  </div>
  </div>
 <div class="form-row">
  <div class="form -btn-actions col">
    <a href="{% url 'produtos:produto_index' %}" class="btn btn-default"><< Voltar</a>
  </div>
</div>
</div>
{% include "util/paginator.html" %}
{% endblock %}