energiaSolar/apps/clientes/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r"^$", views.ClienteView.as_view(), name="cliente_index"),
    url(r"^cliente/detalhes/(?P<pk>[0-9]+)/$",views.ClienteDetailView.as_view(), name="cliente_show"),
    url(r"^cliente/cadastrar/$",views.cliente_create, name="cliente_create"),
    url(r"^cliente/(?P<pk>[0-9]+)/editar/$",views.cliente_edit, name="cliente_edit"),
    url(r"^cliente/(?P<pk>[0-9]+)/excluir/$", views.cliente_delete, name="cliente_delete")
]

energiaSolar/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from .apps.authorization import views
from .apps.core.views import home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', login_required(home), name="root_path" ),
    url(r'^core/', include('energiaSolar.apps.core.urls', namespace='core')),
    url(r'^auth/',
        include('energiaSolar.apps.authorization.urls', namespace='authorization')),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^clientes/',
        include('energiaSolar.apps.clientes.urls', namespace='clientes')),
    url(r'^produtos/',
        include('energiaSolar.apps.produtos.urls', namespace='produtos')),
    url(r'^administracao/',
         include('energiaSolar.apps.administracao.urls', namespace='administracao')),
    url(r'^configuracoes/',
        include('energiaSolar.apps.configuracoes.urls', namespace='configuracoes')),
    url(r'^orcamentos/',
        include('energiaSolar.apps.orcamentos.urls', namespace='orcamentos')),
    url(r'^fornecedores/',
        include('energiaSolar.apps.fornecedores.urls', namespace='fornecedores'))
]

energiaSolar/apps/clientes/models.py
# -*- coding: utf-8 -*-
from django.db import models
from ..configuracoes.models import Regiao, TipoTarifa
from django.utils import timezone

class Cliente(models.Model):
    nome = models.CharField(max_length=90, null=True, blank=True)
    logradouro = models.CharField(max_length=90, null=True, blank=True)
    numero = models.CharField(max_length=10, null=True, blank=True)
    complemento = models.CharField(max_length=50, null=True, blank=True)
    cep = models.CharField(max_length=12, null=True, blank=True)
    bairro = models.CharField(max_length=60, null=True, blank=True)
    cidade = models.CharField(max_length=90, null=True, blank=True)
    uf = models.CharField(max_length=2, null=True, blank=True)
    telefone = models.CharField(max_length=20, null=True, blank=True)
    email = models.EmailField(max_length=100, null=True, blank=True)
    cod_uc = models.CharField(max_length=20, null=True, blank=True)
    consumo = models.CharField(max_length=20, null=True, blank=True)
    rede = models.CharField(max_length=20, null=True, blank=True)
    regiao = models.ForeignKey(Regiao, null=True, blank=True, on_delete=models.CASCADE)
    observacoes = models.TextField(max_length=8192, null=True, blank=True)
    tarifa = models.ForeignKey(TipoTarifa, null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        permissions = (
            ("pode_cadastrar_cliente", "Pode cadastrar cliente"),
            ("pode_alterar_cliente", "Pode editar cliente"),
            ("pode_excluir_cliente", "Pode excluir cliente"),
        )

    def __str__(self):
        return self.nome

energiaSolar/apps/clientes/forms.py
# -*- coding: utf-8 -*-
from django import forms
from datetime import datetime
from .models import Cliente
from ..configuracoes.models import Regiao, TipoTarifa
from localflavor.br.forms import BRStateChoiceField

REDE = (
    ("-------", "-------"),
    ("Monofásica", "Monofásica"),
    ("Trifásica", "Trifásica"),
)

class SearchCliente(forms.Form):
    """Formulário para consulta de clientes da view que lista clientes
    de forma genérica"""

    nome = forms.CharField(max_length=90, required=False)
    cod_uc = forms.CharField(required=False, label="Und. Consumidora")
    regiao = forms.ModelChoiceField(queryset=Regiao.objects.all(), required=False, label="Região")

class ClienteCreateForm(forms.ModelForm):
    """Formulário para criação de ocorrências"""
    uf = BRStateChoiceField(label="UF")
    cep = forms.CharField(required=True, label="CEP")
    numero = forms.CharField(required=True, label="Número")
    cod_uc = forms.CharField(required=True, label="Und. Consumidora")
    consumo = forms.CharField(required=True, label="Consumo Médio")
    rede = forms.ChoiceField(required=True, label="Rede", choices=REDE)
    regiao = forms.ModelChoiceField(queryset=Regiao.objects.all(), required=True, label="Região")
    tarifa = forms.ModelChoiceField(queryset=TipoTarifa.objects.all(), required=True, label="Tarifa")

    class Meta:
        model = Cliente
        fields = ('__all__')
        labels = {
            'observacoes' : 'Informações Adicionais'
        }

energiaSolar/apps/clientes/views.py
# -*- coding: utf-8 -*-
from django.urls import reverse_lazy as reverse
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import get_object_or_404, redirect, render
from ..core.generic_views import SearchCustomView, CustomDetailView
from .forms import SearchCliente, ClienteCreateForm
from .models import Cliente
from ..configuracoes.models import IncidenciaMes, IncidenciaSolar
from django.http import HttpResponse


@method_decorator(login_required, name='dispatch')
class ClienteView(SearchCustomView):
    """
    View para consulta de clientes
    """
    form_class = SearchCliente
    model = Cliente
    order_field = "nome"
    template_name = "clientes/index.html"
    page_title = "Clientes"
    breadcrumbs = [
        (reverse("root_path"), "Início"),
        (reverse("clientes:cliente_index"), "Clientes")
    ]

    def get_queryset(self):
        """
        Altera o filtro do cliente ::
        """
        queryset = super(ClienteView, self).get_queryset()
        form = self.form_class(self.request.GET)
        form.is_valid()
        query = {}

        # Criando nova biblioteca com os valores preenchidos
        for key, value in form.cleaned_data.items():
            if value and value != "":
                query[key] = value

        queryset = queryset.filter(**query)
        return queryset

@method_decorator(login_required, name='dispatch')
class ClienteDetailView(CustomDetailView):
    """
    View para exibição dos detalhes do cliente
    """
    model = Cliente
    template_name = "clientes/detail.html"
    page_title = "Cliente"

    def get_context_data(self, **kwargs):
        context = super(ClienteDetailView, self).get_context_data(**kwargs)
        context["breadcrumbs"] = [
            (reverse("root_path"), "Início"),
            (reverse("clientes:cliente_index"), "Clientes"),
            ("#", self.get_object().id)
        ]

        return context

@login_required
def cliente_create(request):
    """View para Criar um cliente"""
    breadcrumbs = [
        (reverse("root_path"), "Início"),
        (reverse("clientes:cliente_index"), "Clientes"),
        (reverse("clientes:cliente_create"), "Novo Cliente")
    ]

    form = ClienteCreateForm()
    if request.method == 'POST':
        form = ClienteCreateForm(request.POST, request.FILES)

        if form.is_valid():
            cliente = form.save(commit=False)
            cliente.save()

            messages.success(request, "Cliente cadastrado com sucesso")
            return redirect(reverse("clientes:cliente_show", args=[cliente.pk]))

    return render(request, "clientes/cadastro.html", locals())

@login_required
def cliente_edit(request, pk):
    """"View para Editar os Clientes"""
    cliente = get_object_or_404(Cliente, pk=pk)

    breadcrumbs = [
        (reverse("root_path"), "Início"),
        (reverse("clientes:cliente_index"), "Clientes"),
        (reverse("clientes:cliente_show", args=[pk]), cliente.id),
        ("#", "Editar")
    ]

    form = ClienteCreateForm(instance=cliente)

    if request.method == 'POST':
        form = ClienteCreateForm(request.POST, request.FILES, instance=cliente)

        if form.is_valid():
            cliente = form.save(commit=False)
            cliente.save()

            messages.success(request, "Cliente alterado com sucesso.")
            return redirect(reverse("clientes:cliente_show", args=[cliente.pk]))

    return render(request, "clientes/editar.html", locals())

@login_required
def cliente_delete(request, pk):
    """
    View responsável por deletar um cliente
    """
    cliente = get_object_or_404(Cliente, pk=pk)

    cliente.delete()
    messages.success(request, "Cliente deletado com sucesso!")
    return HttpResponse("Cliente deletado com sucesso!")

energiaSolar/apps/clientes/templates/clientes/base.html
{% extends "layout/base.html" %}
{% load staticfiles %}

{% block head_stylesheet %}
<link rel="stylesheet" href="{% static 'css/cliente.css' %}">
{% endblock head_stylesheet %}

energiaSolar/apps/clientes/templates/clientes/cadastro.html
{% extends "layout/base.html" %}
{% load static bootstrap3 core %}
{% block head_stylesheet %}
<link rel="stylesheet" href="{% static 'css/cliente.css' %}">
{% endblock head_stylesheet %}

{% block content %}
<div class="container-fluid">
  <div class="row list">
    <div class="col">
      <!-- search form -->
      <h1>Cadastrar Cliente</h1>
      <form class="form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form_errors form error_types="all" %}
        {% include "clientes/form.html" %}
        <div class="form-row">
          <div class="form -btn-actions col">
            <button class="btn btn-success mr-2">Salvar</button>
            <a href="{% url 'clientes:cliente_index' %}" class="btn">Cancelar</a>
          </div>
        </div>
      </form>
    </div>
  </div>

</div>
{% include "util/paginator.html" %}
{% endblock %}

energiaSolar/apps/clientes/templates/clientes/detail.html
{% extends "clientes/base.html" %}
{% load static bootstrap3 core %}
{% block head_stylesheet %}
<link rel="stylesheet" href="{% static 'css/cliente.css' %}">
{% endblock head_stylesheet %}

{% block content %}
<div class="detail-page">
  <div class="container-fluid">
    <div class="row">
      <div class="col">

        <div class="section-bar">
          <h1 class="title">{{ page_title }}: {{ cliente.id }}</h1>
        </div>
        <table class="table table-bordered table-striped">
          <tr>
            <td><strong>Nome:</strong><br> {{ cliente.nome|default:"Não informado" }}</td>
            <td><strong>Und. Consumidora:</strong><br> {{ cliente.cod_uc|default:"Não informado" }}</td>
            <td><strong>Telefone:</strong><br> {{ cliente.telefone|default:"Não informado" }}</td>
            <td><strong>Email:</strong><br> {{ cliente.email|default:"Não informado" }}</td>
          </tr>
          <tr>
            <td><strong>Endereço:</strong><br> {{ cliente.logradouro|default:"Não informado" }}</td>
            <td><strong>Número:</strong><br> {{ cliente.numero|default:"Não informado" }}</td>
            <td><strong>Complemento:</strong><br> {{ cliente.complemento|default:"Não informado" }}</td>
            <td><strong>CEP:</strong><br> {{ cliente.cep|default:"Não informado" }}</td>
          </tr>
          <tr>
            <td><strong>Cidade:</strong><br> {{ cliente.cidade|default:"Não informado" }}</td>
            <td><strong>Bairro:</strong><br> {{ cliente.bairro|default:"Não informado" }}</td>
            <td><strong>UF:</strong><br> {{ cliente.uf|default:"Não informado" }}</td>
            <td><strong>Consumo:</strong><br> {{ cliente.consumo|default:"Não informado" }} kWh/mês</td>
          </tr>
          <tr>
            <td><strong>Rede:</strong><br> {{ cliente.rede|default:"Não informado" }}</td>
            <td><strong>Regiao:</strong><br> {{ cliente.regiao|default:"Não informado" }}</td>
            <td colspan="2"></td>

          </tr>
          <tr>
             <td colspan="6"><strong>Observações:</strong><br> {{ cliente.observacoes|default:"Não informado" }}</td>
          </tr>
        </table>
      </div>
    </div>
  </div>
  <div class="form-row">
    <div class="form -btn-actions col">
      <a href="{% url 'clientes:cliente_index' %}" class="btn btn-default"><< Voltar</a>
    </div>
  </div>
</div>
{% include "util/paginator.html" %}
{% endblock %}

energiaSolar/apps/clientes/templates/clientes/editar.html
{% extends "layout/base.html" %}
{% load static bootstrap3 core %}
{% block head_stylesheet %}
<link rel="stylesheet" href="{% static 'css/cliente.css' %}">
{% endblock head_stylesheet %}

{% block extra_js %}
<script src="{% static 'js/cliente.js' %}" charset="utf-8"></script>
{% endblock extra_js %}


{% block content %}
<div class="container-fluid">
  <div class="row list">
    <div class="col">
      <!-- search form -->
      <h1>Editar Cliente</h1>
      <ol class="breadcrumb">
        <li class="active">Preencha os campos corretamente</li>
      </ol>
      <form class="form" method="POST">
        {% csrf_token %}
        {% include "clientes/form_edit.html" %}
        <!-- {% bootstrap_form form %} -->
        <div class="form-row">
          <div class="form -btn-actions col">
            <button class="btn btn-success mr-2">Salvar</button>
            <a href="{% url 'clientes:cliente_index' %}" class="btn">Cancelar</a>
          </div>
        </div>
      </form>
    </div>
  </div>

</div>
{% include "util/paginator.html" %}
{% endblock %}

energiaSolar/apps/clientes/templates/clientes/form.html
{% load static bootstrap3 core %}

{% bootstrap_form_errors form error_types="non_field_errors" %}

{{ form.media.css }}
<div class="form-row">
  <div class="col-6">
    {% bootstrap_field form.nome required_css_class="required" %}
  </div>
  <div class="col-3">
    {% bootstrap_field form.telefone required_css_class="required" %}
  </div>
  <div class="col-3">
    {% bootstrap_field form.email required_css_class="required" %}
  </div>
</div>
<div class="form-row">
  <div class="col-3">
    {% bootstrap_field form.cep required_css_class="required" %}
  </div>
  <div class="col-5">
    {% bootstrap_field form.logradouro required_css_class="required" %}
  </div>
  <div class="col-2">
    {% bootstrap_field form.numero required_css_class="required" %}
  </div>
  <div class="col-2">
    {% bootstrap_field form.complemento required_css_class="required" %}
  </div>
</div>
<div class="form-row">
  <div class="col-5">
    {% bootstrap_field form.cidade required_css_class="required" %}
  </div>
  <div class="col-4">
    {% bootstrap_field form.bairro required_css_class="required" %}
  </div>
  <div class="col-3">
    {% bootstrap_field form.uf required_css_class="required" %}
  </div>
</div>
<div class="form-row">
  <div class="col-3">
    {% bootstrap_field form.cod_uc required_css_class="required" %}
  </div>
  <div class="col-3">
    {% bootstrap_field form.consumo required_css_class="required" %}
  </div>
  <div class="col-3">
    {% bootstrap_field form.rede required_css_class="required" %}
  </div>
  <div class="col-3">
    {% bootstrap_field form.regiao required_css_class="required" %}
  </div>
  <div class="col-4">
    {% bootstrap_field form.tarifa required_css_class="required" %}
  </div>
</div>
<div class="form-row">
  <div class="col-12">
    {% bootstrap_field form.observacoes required_css_class="required" %}
  </div>
</div>
{{ form.media.js }}
{% block extra_js %}
<script type="text/javascript" src="{% static 'js/jquery.mask.min.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
<script src="{% static 'js/cliente.js' %}" charset="utf-8"></script>
{% endblock extra_js %}

energiaSolar/apps/clientes/templates/clientes/form_edit.html
{% load static bootstrap3 core %}
{% bootstrap_form_errors form error_types="non_field_errors" %}
{{ form.errors }}
<div class="form-row">
  <div class="col-6">
    {% bootstrap_field form.nome required_css_class="required" %}
  </div>
  <div class="col-3">
    {% bootstrap_field form.telefone required_css_class="required" %}
  </div>
  <div class="col-3">
    {% bootstrap_field form.email required_css_class="required" %}
  </div>
</div>
<div class="form-row">
  <div class="col-3">
    {% bootstrap_field form.cep required_css_class="required" %}
  </div>
  <div class="col-5">
    {% bootstrap_field form.logradouro required_css_class="required" %}
  </div>
  <div class="col-2">
    {% bootstrap_field form.numero required_css_class="required" %}
  </div>
  <div class="col-2">
    {% bootstrap_field form.complemento required_css_class="required" %}
  </div>
</div>
<div class="form-row">
  <div class="col-5">
    {% bootstrap_field form.cidade required_css_class="required" %}
  </div>
  <div class="col-4">
    {% bootstrap_field form.bairro required_css_class="required" %}
  </div>
  <div class="col-3">
    {% bootstrap_field form.uf required_css_class="required" %}
  </div>
</div>
<div class="form-row">
  <div class="col-3">
    {% bootstrap_field form.cod_uc required_css_class="required" %}
  </div>
  <div class="col-3">
    {% bootstrap_field form.consumo required_css_class="required" %}
  </div>
  <div class="col-3">
    {% bootstrap_field form.rede required_css_class="required" %}
  </div>
  <div class="col-3">
    {% bootstrap_field form.regiao required_css_class="required" %}
  </div>
  <div class="col-4">
    {% bootstrap_field form.tarifa required_css_class="required" %}
  </div>
</div>
<div class="form-row">
  <div class="col-12">
    {% bootstrap_field form.observacoes required_css_class="required" %}
  </div>
</div>

energiaSolar/apps/clientes/templates/clientes/index.html
{% extends "clientes/base.html" %}
{% load static bootstrap3 core %}
{% block head_stylesheet %}
<link rel="stylesheet" href="{% static 'css/cliente.css' %}">
{% endblock head_stylesheet %}

{% block content %}
<div class="container-fluid">

  <div class="row">
    <div class="col">
      <div class="section-bar">
        <h1 class="title">{{ page_title }}</h1>

      </div>
    </div>
  </div>
  <div class="row-list">
    <div class="col">
      <!-- search form -->
      <form class="form form-flex form-search-cerin">
        {% bootstrap_form form %}
        <div class="form-group">
          <div id="general-search-button"></div>
        </div>
      </form>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <table class="table table-bordered table-striped">
        <thead>
          <th>Ações</th>
          <th>Nome</th>
          <th>Telefone </th>
          <th>Email </th>
          <th>Cidade</th>
        </thead>
        <tbody>
          {% for cliente in object_list %}
            <tr>
              <td>
                <a class="btn-magnify" href="{% url 'clientes:cliente_show' cliente.pk %}" title="Ver detalhes">
                  <span class="mdi mdi-magnify mdi-18px"></span>
                </a>
                <a class="btn-magnify" href="{% url 'clientes:cliente_edit' cliente.pk %}" title="Editar">
                  <span class="mdi mdi-pencil mdi-18px"></span>
                </a>
                <a class="btn-magnify" href="javascript:clienteDelete({{cliente.pk}});" title="Excluir">
                  <span class="mdi mdi-delete mdi-18px"></span>
                </a>
              </td>
              <td>{{ cliente.nome|default:"Não informado"}}</td>
              <td>{{ cliente.telefone|default:"Não informado"}}</td>
              <td>{{ cliente.email|default:"Não informado"}}</td>
              <td>{{ cliente.cidade|default:"Não informado"}}</td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
      <!-- Modal responsável pela confirmação
        da exclusão de um cliente -->
        <div id="myModal" class="modal" tabindex="-1" role="dialog">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Confirmar Exclusão</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p>Você tem certeza que deseja excluir permanentemente esse cliente?</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" id="excluirCliente" class="btn btn-primary">Excluir</button>
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>

</div>
{% include "util/paginator.html" %}
{% endblock %}

{% block extra_js %}
<script>
  $('#messageDelete').hide();
  function clienteDelete(pk){
      $('#myModal').modal('toggle')
      $( "#excluirCliente" ).click(function() {
        $.ajax({
          url: '/clientes/cliente/'+pk+'/excluir',
          success: function(data) {
            location.reload();
          }
        });
      });
   };
</script>
{% endblock %}