energiaSolar/apps/configuracoes/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r"^$", views.TabelaSolarView.as_view(), name="configuracoes_index"),
    url(r"^tabela/cadastrar/$",views.tabela_create, name="tabela_create"),
    url(r"^tabela/detalhes/(?P<pk>[0-9]+)/$",views.tabela_detalhes, name="tabela_show"),
    url(r"^tabela/editar/(?P<pk>[0-9]+)/$",views.tabela_edit, name="tabela_edit"),
    url(r"^tabela/(?P<pk>[0-9]+)/excluir/$", views.tabela_delete, name="tabela_delete"),
    url(r"^reajuste/$", views.reajustar_valor, name="reajustar_valor"),
    url(r"^tarifas/$", views.TarifasView.as_view(), name="tarifas_index"),
    url(r"^tarifas/cadastrar/$", views.tarifa_energia, name="tarifa_energia"),
    url(r"^tarifas/detalhes/(?P<pk>[0-9]+)/$", views.TarifasDetailView.as_view(), name="tarifas_show"),
    url(r"^tarifas/editar/(?P<pk>[0-9]+)/$", views.tarifas_edit, name="tarifas_edit"),
    url(r"^tarifas/(?P<pk>[0-9]+)/excluir/$", views.tarifa_delete, name="tarifas_delete"),

]

energiaSolar/apps/produtos/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r"^$", views.ProdutoView.as_view(), name="produto_index"),
    url(r"^produto/detalhes/(?P<pk>[0-9]+)/$",views.ProdutoDetailView.as_view(), name="produto_show"),
    url(r"^produto/cadastrar/$",views.produto_create, name="produto_create"),
    url(r"^produto/(?P<pk>[0-9]+)/editar/$",views.produto_edit, name="produto_edit"),
    url(r"^produto/(?P<pk>[0-9]+)/excluir/$",views.produto_delete, name="produto_delete"),
    url(r"^itens/$", views.ItemView.as_view(), name="itens_index"),
    url(r"^produto/itens/(?P<pk>[0-9]+)/editar/$",views.itens_edit, name="itens_edit"),
    url(r"^produto/itens/(?P<pk>[0-9]+)/detalhes/$",views.ItemDetailView.as_view(), name="item_show"),
]

energiaSolar/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from .apps.authorization import views
from .apps.core.views import home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', login_required(home), name="root_path" ),
    url(r'^core/', include('energiaSolar.apps.core.urls', namespace='core')),
    url(r'^auth/',
        include('energiaSolar.apps.authorization.urls', namespace='authorization')),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^clientes/',
        include('energiaSolar.apps.clientes.urls', namespace='clientes')),
    url(r'^produtos/',
        include('energiaSolar.apps.produtos.urls', namespace='produtos')),
    url(r'^administracao/',
         include('energiaSolar.apps.administracao.urls', namespace='administracao')),
    url(r'^configuracoes/',
        include('energiaSolar.apps.configuracoes.urls', namespace='configuracoes')),
    url(r'^orcamentos/',
        include('energiaSolar.apps.orcamentos.urls', namespace='orcamentos')),
    url(r'^fornecedores/',
        include('energiaSolar.apps.fornecedores.urls', namespace='fornecedores'))
]

energiaSolar/apps/configuracoes/models.py
from django.db import models

class Regiao(models.Model):
    descricao = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.descricao

class TipoTarifa(models.Model):
    descricao = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.descricao

class IncidenciaMes(models.Model):
    descricao = models.CharField(max_length=20, null=True, blank=True)
    valor = models.CharField(max_length=5, null=True, blank=True)
    regiao = models.ForeignKey(Regiao, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.descricao

class IncidenciaSolar(models.Model):
    regiao = models.ForeignKey(Regiao, null=True, blank=True, on_delete=models.CASCADE)
    media = models.CharField(max_length=5, null=True, blank=True)

    def __int__(self):
        return self.regiao

class Tarifas(models.Model):
    valor = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=2)
    tipo = models.ForeignKey(TipoTarifa, null=True, blank=True, on_delete=models.CASCADE)

    def __float__(self):
        return self.valor

energiaSolar/apps/configuracoes/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import  Regiao, IncidenciaMes, TipoTarifa, Tarifas
from energiaSolar.apps.produtos.models import *

TIPO_AJUSTE = (
    ('Aumento', 'Aumento'),
    ('Redução', 'Redução'),
)

MESES = (
    ('Janeiro', 'Janeiro'),
    ('Fevereiro', 'Fevereiro'),
    ('Março', 'Março'),
    ('Abril', 'Abril'),
    ('Maio', 'Maio'),
    ('Junho', 'Junho'),
    ('Julho', 'Julho'),
    ('Agosto', 'Agosto'),
    ('Setembro', 'Setembro'),
    ('Outubro', 'Outubro'),
    ('Novembro', 'Novembro'),
    ('Dezembro', 'Dezembro')
)

class SearchTabela(forms.Form):
    """Formulário para consulta das tabelas da view que lista  tabelas de sol
    de forma genérica"""

    regiao = forms.CharField(max_length=90, required=False)

class SearchTarifas(forms.Form):
    """Formulário para consulta das tarifas"""

    valor = forms.DecimalField(required=False)
    tipo = forms.ModelChoiceField(queryset=TipoTarifa.objects.all(), required=False)

class IncidenciaCreateForm(forms.ModelForm):
    """Formulário para importação dos dados da incidência solar"""

    regiao = forms.ModelChoiceField(queryset=Regiao.objects.all(), required=True)

    class Meta:
        model = IncidenciaMes
        fields = ("__all__")

class IncidenciaEditForm(forms.ModelForm):
    """Formulário para importação dos dados da incidência solar"""

    regiao = forms.ModelChoiceField(queryset=Regiao.objects.all(), required=False)

    class Meta:
        model = IncidenciaMes
        exclude = ['regiao']

class ReajusteCreateForm(forms.ModelForm):
    """Formulário para reajustar valores"""

    percentual = forms.FloatField(required=True, widget=forms.TextInput(
                    attrs={'type': 'number','id':'percentual','min': '0','max':'10','step':'0.01'}))
    tipo_ajuste = forms.ChoiceField(label="Tipo do Ajuste", choices=TIPO_AJUSTE, required=True)

    class Meta:
        model = Produto
        exclude = '__all__'

class TarifasCreateForm(forms.ModelForm):
    """Formulário criação da tarifa de energia"""

    valor = forms.DecimalField(required=True)
    tipo = forms.ModelChoiceField(queryset=TipoTarifa.objects.all().order_by('descricao'), required=True)

    class Meta:
        model = Tarifas
        fields = ("__all__")

energiaSolar/apps/configuracoes/views.py
from django.shortcuts import render
from django.urls import reverse_lazy as reverse
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import get_object_or_404, redirect, render
from .forms import *
from energiaSolar.apps.produtos.models import Produto, Item
from .models import IncidenciaSolar, IncidenciaMes, Regiao, Tarifas
from ..core.generic_views import SearchCustomView,CustomDetailView
from django.http import HttpResponse

@method_decorator(login_required, name='dispatch')
class TabelaSolarView(SearchCustomView):
    """
    View para consulta de clientes
    """
    form_class = SearchTabela
    model = IncidenciaSolar
    order_field = "regiao"
    template_name = "configuracoes/index.html"
    page_title = "Configuracões"
    breadcrumbs = [
        (reverse("root_path"), "Início"),
        (reverse("configuracoes:configuracoes_index"), "Configurações")
    ]

    def get_queryset(self):
        """
        Altera o filtro do cliente ::
        """
        queryset = super(TabelaSolarView, self).get_queryset()
        form = self.form_class(self.request.GET)
        form.is_valid()
        query = {}

        # Criando nova biblioteca com os valores preenchidos
        for key, value in form.cleaned_data.items():
            if value and value != "":
                query[key] = value

        queryset = queryset.filter(**query)
        return queryset

@method_decorator(login_required, name='dispatch')
class TarifasView(SearchCustomView):
    """
    View para consulta de tarifas
    """
    form_class = SearchTarifas
    model = Tarifas
    order_field = "tipo"
    template_name = "configuracoes/tarifas_index.html"
    page_title = "Configuracões"
    breadcrumbs = [
        (reverse("root_path"), "Início"),
        (reverse("configuracoes:tarifas_index"), "Tarifas")
    ]

    def get_queryset(self):
        """
        Altera o filtro da tarifa ::
        """
        queryset = super(TarifasView, self).get_queryset()
        form = self.form_class(self.request.GET)
        form.is_valid()
        query = {}

        # Criando nova biblioteca com os valores preenchidos
        for key, value in form.cleaned_data.items():
            if value and value != "":
                query[key] = value

        queryset = queryset.filter(**query)
        return queryset

@method_decorator(login_required, name='dispatch')
class TarifasDetailView(CustomDetailView):
    """
    View para exibição dos detalhes das tarifas
    """
    model = Tarifas
    template_name = "configuracoes/tarifas_detail.html"
    page_title = "Tarifas"

    def get_context_data(self, **kwargs):
        context = super(TarifasDetailView, self).get_context_data(**kwargs)
        context["breadcrumbs"] = [
            (reverse("root_path"), "Início"),
            (reverse("configuracoes:tarifas_index"), "Tarifas"),
            ("#", self.get_object().id)
        ]

        return context


def tabela_detalhes(request, pk):
    """
    View para exibição dos detalhes das tabelas de energia solar
    """
    breadcrumbs = [
        (reverse("root_path"), "Início"),
        (reverse("configuracoes:tabela_create"), "Configurações"),
        (reverse("configuracoes:configuracoes_create"), "Configurações")
    ]

    tabela = IncidenciaMes.objects.filter(regiao=pk)
    incidencia_solar = get_object_or_404(IncidenciaSolar, regiao=pk)

    return render(request, "configuracoes/detail.html", locals())

@login_required()
def tabela_create(request):
    """
    View para importação do CSV com os dados da tabela de sol
    """
    breadcrumbs = [
        (reverse("root_path"), "Início"),
        (reverse("configuracoes:tabela_create"), "Tabelas de Sol"),
        (reverse("configuracoes:configuracoes_create"), "Tabelas de Sol")
    ]
    meses = ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun',
             'Jul','Ago', 'Set', 'Out', 'Nov', 'Dez']

    form = IncidenciaCreateForm()

    if request.method == 'POST':
        form = IncidenciaCreateForm(request.POST)

        if form.is_valid():
            tabela = form.save(commit=False)

            valores = request.POST.getlist('valores[]')
            regiao = form['regiao'].value()

            regiao = get_object_or_404(Regiao, pk=regiao)

            if valores:
                for valor, mes in zip(valores, meses):
                    tabela = IncidenciaMes.objects.get_or_create(descricao=mes, regiao=regiao)[0]
                    tabela.valor = valor
                    tabela.save()

                incidencia_mes = IncidenciaMes.objects.filter(regiao=regiao)

                soma = 0
                for i in incidencia_mes:
                    soma += int(i.valor)

                incidencia_solar = IncidenciaSolar.objects.get_or_create(regiao=regiao)[0]

                if incidencia_solar:
                    incidencia_solar.media = int(soma / 12)
                    incidencia_solar.save()

            messages.success(request, "Configurações cadastradas com sucesso")
            return redirect(reverse("configuracoes:tabela_show", args=[regiao.pk]))

    return render(request, "configuracoes/form.html", locals())

@login_required()
def tabela_edit(request, pk):
    """
    View para importação do CSV com os dados da tabela de sol
    """
    tabela = IncidenciaMes.objects.filter(regiao_id=pk)
    regiao = get_object_or_404(Regiao, pk=pk)

    breadcrumbs = [
        (reverse("root_path"), "Início"),
        (reverse("configuracoes:tabela_create"), "Tabelas de Sol"),
        (reverse("configuracoes:configuracoes_create"), "Tabelas de Sol")
    ]
    meses = ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun',
             'Jul','Ago', 'Set', 'Out', 'Nov', 'Dez']

    form = IncidenciaEditForm(instance=regiao)

    if request.method == 'POST':
        form = IncidenciaEditForm(request.POST, instance=regiao)

        if form.is_valid():
            tabela = form.save(commit=False)
            valores = request.POST.getlist('valores[]')

            if valores:
                for valor, mes in zip(valores, meses):
                    tabela = IncidenciaMes.objects.get_or_create(descricao=mes, regiao=regiao)[0]
                    tabela.valor = valor
                    tabela.save()

                incidencia_mes = IncidenciaMes.objects.filter(regiao=regiao)

                soma = 0
                for i in incidencia_mes:
                    soma += int(i.valor)

                incidencia_solar = IncidenciaSolar.objects.get_or_create(regiao=regiao)[0]

                if incidencia_solar:
                    incidencia_solar.media = int(soma / 12)
                    incidencia_solar.save()

        messages.success(request, "Configurações editadas com sucesso")
        return redirect(reverse("configuracoes:tabela_show", args=[regiao.pk]))

    return render(request, "configuracoes/form_edit_tabela.html", locals(), {"form" : form})

@login_required
def reajustar_valor(request):
    """View reajustar os valores dos produtos"""
    breadcrumbs = [
        (reverse("root_path"), "Início"),
        (reverse("configuracoes:reajustar_valor"), "Reajustar Valor dos Produtos")
    ]

    form = ReajusteCreateForm()
    if request.method == 'POST':
        form = ReajusteCreateForm(request.POST)

        if form.is_valid():
            produto = form.save(commit=False)
            lista_produtos = Produto.objects.all()
            percentual = float(form.cleaned_data['percentual'])

            for produto in lista_produtos:
                valor_produto = float(produto.valor)
                valor_reajustado = ((valor_produto * percentual) / 100)

                if form.cleaned_data['tipo_ajuste'] == 'Aumento':
                    produto.valor = float(produto.valor) + valor_reajustado

                elif form.cleaned_data['tipo_ajuste'] == 'Redução':
                    produto.valor = float(produto.valor) - valor_reajustado

                if produto.porcentagem_estrutura_produto and produto.porcentagem_servico_produto:
                    produto.valor_servico = (produto.porcentagem_servico_produto * produto.valor) / 100
                    produto.valor_est_metalica = (produto.porcentagem_estrutura_produto * produto.valor) / 100
                    produto.valor_individual_metalica = int(produto.valor_est_metalica / produto.estrutura_metalica)

                #Calcula o percentual de reajuste dos itens do produto se houver
                itens = Item.objects.filter(produto=produto.pk)

                for item in itens:
                    valor_item_reajustado = (produto.valor * item.porcentagem_valor_produto) / 100

                    item.valor_item = float(valor_item_reajustado)
                    item.valor_unitario = (item.valor_item / int(item.quantidade))

                    item.save()

                produto.save()

            messages.success(request, "Reajuste realizado com sucesso")
            return redirect(reverse("produtos:produto_index"))

    return render(request, "configuracoes/reajustar_index.html", locals())

def tarifa_energia(request):
    """
    View para editar a tarifa de energia
    """
    breadcrumbs = [
        (reverse("root_path"), "Início"),
        (reverse("configuracoes:tarifa_energia"), "Tarifas"),
    ]

    form = TarifasCreateForm()
    if request.method == 'POST':
        form = TarifasCreateForm(request.POST)

        if form.is_valid():
            tarifa = form.save(commit=False)
            tipo = form.cleaned_data['tipo']
            valor = form.cleaned_data['valor']
            tipo_tarifa = TipoTarifa.objects.filter(pk=tipo.pk)[0]
            tarifa = Tarifas.objects.get_or_create(tipo=tipo_tarifa)[0]
            tarifa.valor = valor
            tarifa.save()

            messages.success(request, "Tarifa cadastrada com sucesso.")
            return redirect(reverse("configuracoes:tarifas_index"))

energiaSolar/apps/configuracoes/templates/configuracoes/detail.html
{% extends "clientes/base.html" %}
{% load static bootstrap3 core %}
{% block head_stylesheet %}
<link rel="stylesheet" href="{% static 'css/cliente.css' %}">
{% endblock head_stylesheet %}

{% block content %}
<div class="detail-page">
  <div class="container-fluid">
    <div class="row">
      <div class="col">

        <div class="section-bar">
          <h1 class="title">Incidência Solar</h1>
        </div>
        <table class="table table-bordered table-striped">
          <thead>
            <th>Mês</th>
            <th>Valor</th>
          </thead>

            {% for dado in tabela %}
              <tr>
                <td>{{ dado.descricao|default:"Não informado" }}</td>
                <td>{{ dado.valor|default:"Não informado" }}</td>
              </tr>
            {% endfor %}
           <tr>
              {% for dado in tabela|slice:":1" %}
                <td><strong>Região: </strong>{{dado.regiao}}</td>
              {% endfor %}
             <td><strong>Média: </strong>{{ incidencia_solar.media}}</td>
            </tr>
        </table>
      </div>
    </div>
  </div>
  <div class="form-row">
    <div class="form -btn-actions col">
      <a href="{% url 'configuracoes:configuracoes_index' %}" class="btn btn-default"><< Voltar</a>
    </div>
  </div>
</div>
{% include "util/paginator.html" %}
{% endblock %}

energiaSolar/apps/configuracoes/templates/configuracoes/editar.html
{% extends "layout/base.html" %}
{% load static bootstrap3 core %}
{% block head_stylesheet %}
<link rel="stylesheet" href="{% static 'css/cliente.css' %}">
{% endblock head_stylesheet %}

{% block extra_js %}
<script src="{% static 'js/cliente.js' %}" charset="utf-8"></script>
{% endblock extra_js %}


{% block content %}
<div class="container-fluid">
  <div class="row list">
    <div class="col">
      <!-- search form -->
      <h1>Editar Configurações</h1>
      <ol class="breadcrumb">
        <li class="active">Preencha os campos corretamente</li>
      </ol>
      <form class="form" method="POST">
        {% csrf_token %}
        {% include "configuracoes/form_edit.html" %}
        <!-- {% bootstrap_form form %} -->
        <div class="form-row">
          <div class="form -btn-actions col">
            <button class="btn btn-success mr-2">Salvar</button>
            <a href="{% url 'configuracoes:configuracoes_index' %}" class="btn">Cancelar</a>
          </div>
        </div>
      </form>
    </div>
  </div>

</div>
{% include "util/paginator.html" %}
{% endblock %}

energiaSolar/apps/configuracoes/templates/configuracoes/form_edit_tabela.html
{% extends "layout/base.html" %}
{% load static bootstrap3 core %}
{% bootstrap_form_errors form error_types="non_field_errors" %}

{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <div class="section-bar">
        <h1 class="title">Editar tabela</h1>
      </div>
        <div class="section-bar">
            <h3>Região: {{ regiao }}</h3>
        </div>
    </div>
  </div>
  <div class="row list">
    <div class="col">
      <form class="form" method="POST" novalidate>
        {% csrf_token %}
        {% bootstrap_form_errors form error_types="all" %}
          {{ form.non_field_errors.as_text }}
             <table class="table table-striped table-bordered table-responsive" id="tabela">
                <thead>
                    <tr>
                        {% for mes in meses %}
                            <th class="th-sm">{{ mes }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        {% for i in tabela %}
                            <td>
                                <input class="form-control" name="valores[]" type="text" value="{{ i.valor }}">
                            </td>
                        {% endfor %}
                    </tr>
                </tbody>
          </table>
            <div class="form-row">
              <div class="form -btn-actions col">
                <button class="btn btn-success mr-2" id="salvar">Salvar</button>
                <a href="{% url 'configuracoes:configuracoes_index' %}" class="btn">Cancelar</a>
              </div>
            </div>
        </form>
    </div>
  </div>
</div>
{% include "util/paginator.html" %}
{% endblock %}
{% block extra_js %}
<script type="text/javascript" src="{% static 'js/jquery.mask.min.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
<script src="{% static 'js/incidencia.js' %}" charset="utf-8"></script>
{% endblock extra_js %}

energiaSolar/apps/configuracoes/templates/configuracoes/index.html
{% extends "clientes/base.html" %}
{% load static bootstrap3 core %}
{% block head_stylesheet %}
<link rel="stylesheet" href="{% static 'css/produto.css' %}">
{% endblock head_stylesheet %}

{% block content %}
<div class="container-fluid">

  <div class="row">
    <div class="col">
      <div class="section-bar">
        <h1 class="title">Tabelas de Sol</h1>
         <div class="action-bar">
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="opcoes-processo" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Opções
            </button>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="opcoes-processo">
              <a class="dropdown-item" href="{% url 'configuracoes:tabela_create' %}">Nova Tabela</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <!-- search form -->
      <form class="form form-flex form-search-cerin">
        {% bootstrap_form form %}
        <div class="form-group">
          <div id="general-search-button"></div>
        </div>
      </form>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <table class="table table-striped table-bordered">
        <thead>
          <th>Ações</th>
          <th>Região</th>
          <th>Média</th>
        </thead>
        <tbody>
          {% for objeto in object_list %}
            <tr>
              <td>
                <a class="btn-magnify" href="{% url 'configuracoes:tabela_show' objeto.regiao.pk %}" title="Ver detalhes">
                  <span class="mdi mdi-magnify mdi-18px"></span>
                </a>
                <a class="btn-magnify" href="{% url 'configuracoes:tabela_edit' objeto.regiao.pk  %}" title="Editar">
                  <span class="mdi mdi-pencil mdi-18px"></span>
                </a>
                <a class="btn-magnify" href="javascript:tabelaDelete({{objeto.regiao.pk}});" title="Excluir">
                  <span class="mdi mdi-delete mdi-18px"></span>
                </a>
              </td>
              <td>{{ objeto.regiao|default:"Não informado"}}</td>
              <td>{{ objeto.media|default:"Não informado"}}</td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
      <!-- Modal responsável pela confirmação
        da exclusão de um cliente -->
        <div id="myModal" class="modal" tabindex="-1" role="dialog">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Confirmar Exclusão</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p>Você tem certeza que deseja excluir permanentemente essa tabela?</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" id="excluirTabela" class="btn btn-primary">Excluir</button>
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>

</div>
{% include "util/paginator.html" %}
{% endblock %}

{% block extra_js %}
<script>
  $('#messageDelete').hide();
  function tabelaDelete(pk){
      $('#myModal').modal('toggle')
      $( "#excluirTabela" ).click(function() {
        $.ajax({
          url: '/configuracoes/tabela/'+pk+'/excluir',
          success: function(data) {
            location.reload();
          }
        });
      });
   };
</script>
{% endblock %}

energiaSolar/apps/configuracoes/templates/configuracoes/tarifas_index.html
{% extends "clientes/base.html" %}
{% load static bootstrap3 core %}
{% block head_stylesheet %}
<link rel="stylesheet" href="{% static 'css/produto.css' %}">
{% endblock head_stylesheet %}

{% block content %}
<div class="container-fluid">

  <div class="row">
    <div class="col">
      <div class="section-bar">
        <h1 class="title">Tarifas</h1>
        <div class="action-bar">
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="opcoes-processo" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Opções
            </button>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="opcoes-processo">
              <a class="dropdown-item" href="{% url 'configuracoes:tarifa_energia' %}">Cadastrar</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <!-- search form -->
      <form class="form form-flex form-search-cerin">
        {% bootstrap_form form %}
        <div class="form-group">
          <div id="general-search-button"></div>
        </div>
      </form>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <table class="table table-striped table-bordered">
        <thead>
          <th>Ações</th>
          <th>Valor</th>
          <th>Tipo</th>
        </thead>
        <tbody>
          {% for objeto in object_list %}
            <tr>
              <td>
                  <a class="btn-magnify" href="{% url 'configuracoes:tarifas_show' objeto.pk %}" title="Ver detalhes">
                    <span class="mdi mdi-magnify mdi-18px"></span>
                  </a>
                  <a class="btn-magnify" href="{% url 'configuracoes:tarifas_edit' objeto.pk %}" title="Editar">
                    <span class="mdi mdi-pencil mdi-18px"></span>
                  </a>
                  <a class="btn-magnify" href="javascript:tarifaDelete({{objeto.pk}});" title="Excluir">
                    <span class="mdi mdi-delete mdi-18px"></span>
                  </a>
              </td>
              <td>{{ objeto.valor|default:"Não informado"}}</td>
              <td>{{ objeto.tipo|default:"Não informado"}}</td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
      <!-- Modal responsável pela confirmação
        da exclusão de uma tarifa -->
        <div id="myModal" class="modal" tabindex="-1" role="dialog">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Confirmar Exclusão</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p>Você tem certeza que deseja excluir permanentemente essa tarifa?</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" id="excluirTarifa" class="btn btn-primary">Excluir</button>
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>

</div>
{% include "util/paginator.html" %}
{% endblock %}

{% block extra_js %}
<script>
  $('#messageDelete').hide();
  function tarifaDelete(pk){
      $('#myModal').modal('toggle')
      $( "#excluirTarifa" ).click(function() {
        $.ajax({
          url: '/configuracoes/tarifas/'+pk+'/excluir',
          success: function(data) {
            location.reload();
          }
        });
      });
   };
</script>
{% endblock %}