energiaSolar/apps/core/urls.py
# -*- coding: utf-8 -*-
from . import views
from django.conf.urls import url

urlpatterns = [
    url(r"^$", views.index, name='index'),
]

energiaSolar/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from .apps.authorization import views
from .apps.core.views import home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', login_required(home), name="root_path" ),
    url(r'^core/', include('energiaSolar.apps.core.urls', namespace='core')),
    url(r'^auth/',
        include('energiaSolar.apps.authorization.urls', namespace='authorization')),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^clientes/',
        include('energiaSolar.apps.clientes.urls', namespace='clientes')),
    url(r'^produtos/',
        include('energiaSolar.apps.produtos.urls', namespace='produtos')),
    url(r'^administracao/',
         include('energiaSolar.apps.administracao.urls', namespace='administracao')),
    url(r'^configuracoes/',
        include('energiaSolar.apps.configuracoes.urls', namespace='configuracoes')),
    url(r'^orcamentos/',
        include('energiaSolar.apps.orcamentos.urls', namespace='orcamentos')),
    url(r'^fornecedores/',
        include('energiaSolar.apps.fornecedores.urls', namespace='fornecedores'))
]

energiaSolar/apps/core/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.views.decorators.cache import cache_page
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

@login_required
def index(request):
    return render(request, 'index.html', locals())

@login_required
def home(request):
    """View padrão do projeto"""
    # Armazena data do último login do usuário logado
    last_login = request.user.last_login
    # Armazena nome completo do usuário logado
    usuario = request.user.first_name

    return render(request, "home.html", locals())

energiaSolar/apps/core/templates/layout/base.html
{% load staticfiles core %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Viva Energia Solar</title>
  <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'vendor/materialdesignicons/css/materialdesignicons.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/icons.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/semob-searchcep.css' %}">
  <link rel="stylesheet" href="{% static 'css/core.css' %}">
  <link rel="shortcut icon" href="{% static 'images/favicon1.png' %}" />
  {% block head_stylesheet %}{% endblock head_stylesheet %}

</head>
<body>
  {% if debug %}<div class="alert-debug">Você está usando a versão de testes</div>{% endif %}
  <div class="wrapper {% if debug %}wrapper-debug{% endif %}" >
    <aside id="sidebar" class="sidebar">
      {% get_menu %}
      <div class="header">
        <a class="page-logo" href="{% url 'root_path' %}"><img src="{% static 'images/logo5.png' %}" /></a>
      </div>
      <ul class="menu">
        {% for app in app_menu %}
        {% has_permission app.permissions as can_view_menu %}
        {% if can_view_menu %}
        <li>
          {% menu_is_used app.items request.path as menu_opened %}
          {% if app.items %}
            <a class="module" href="#{{ app.verbose_name|slugify }}" data-toggle="collapse" aria-expanded="{% if menu_opened %}true{% else %}false{% endif %}">
              <span class="mdi mdi-{{app.icon}} mdi-24px mr-icon-3"> </span><span class="hide-menu">{{ app.verbose_name }}</span>
            </a>
            <ul class="module-items collapse {% if menu_opened %} show {% endif %}" id="{{ app.verbose_name|slugify }}">
              {% for item in app.items %}
              {% has_permission item.permissions as can_access %}
              {% if can_access %}
              <li class="item">
                <a href="{{ item.link }}" {% if item.link|in_list:request.path %} class="active" {% endif %}>{{ item.verbose_name }}</a>
              </li>
              {% endif %}
              {% endfor %}
          </ul>
          {% else %}
            {% if app.login_required == 'True' %}
              {% if user.is_authenticated %}
              <a class="module {% if app.link|in_list:request.path %}active{% endif %}" href="{{ app.link }}">
                <span class="mdi mdi-{{app.icon}} mdi-24px mr-icon-3"></span><span class="hide-menu">{{ app.verbose_name }}</span>
              </a>
              {% endif %}
            {% endif %}
            {% if app.login_required == 'False' %}
              {% if user.is_authenticated %}
              <a class="module {% if app.link|in_list:request.path %}active{% endif %}" href="{{ app.link }}">
                <span class="mdi mdi-{{app.icon}} mdi-24px mr-icon-3"></span><span class="hide-menu">{{ app.verbose_name }}</span>
              </a>
              {% else %}
              <a class="module {% if app.link|in_list:request.path %}active{% endif %}" href="{{ app.link }}">
                <span class="mdi mdi-{{app.icon}} mdi-24px mr-icon-3"></span><span class="hide-menu">{{ app.verbose_name }}</span>
              </a>
              {% endif %}
            {% endif %}
          {% endif %}
        </li>
        {% endif %}
        {% endfor %}

        {% if user.is_authenticated %}
        <li>
          <a class="module -logout" href="{% url 'authorization:logout' %}?next={% url 'root_path' %}">
            <span class="mdi mdi-power mdi-24px"></span> Sair ({{ request.user }})
          </a>
        </li>
        {% endif %}
      </ul>
    </aside>
    <div id="content">
      <div class="container-fluid sidebarButton">
        <a id="sidebarButton" class="btn btn-outline-dark btn-lg">
          <span class="mdi mdi-menu mdi-24px"></span>
        </a>
      </div>
      {% block breadcrumbs %}
        {% include "util/breadcrumbs.html"%}
      {% endblock %}

      {% if messages %}
        <div class="container-fluid">
          {% for message in messages %}
          <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
          {% endfor %}
        </div>
      {% endif %}

      {% block content %}{% endblock %}
    </div>
    <footer class="footer">
      <div class="container-fluid clearfix">
        <span class="float-none float-sm-right text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © 2019</span>
      </div>
    </footer>
  </div>

  <script src="{% static 'vendor/bootstrap/js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/popper.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
  <script type="text/javascript">
    $(document).ready(function () {
      $('#sidebarButton').on('click', function () {
        $('#sidebar').toggleClass('active');
      });
    });
  </script>
  {% block extra_js %}{% endblock extra_js %}
  {% block js %}{% endblock js %}
  <script type="text/javascript" src="{% static 'dist/bundle.js' %}"></script>>
</body>
</html>